version: "3"
services:
  ysuauth_1: #第1个
    image: a645162/ysuauth:latest
#    image: a645162/ysuauth:3.0.2
    restart: always
    container_name: ysuauth
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M
        reservations:
          cpus: '0.2'
          memory: 200M
    network_mode: host
    tty: true
    volumes:
#      - /home/pi/ysuauth/settings:/ysuauth/settings
      - ./settings/:/ysuauth/settings/
#      - /home/pi/ysuauth/log:/ysuauth/log
      - ./logs/:/ysuauth/logs/
    environment:
    # 1、每个学生之间使用&隔开
    # 2、每个学生，请提供其对应密码
    # 3、请将大括号一并删除
      - YSU_AUTH_USER="{201811080333} = {3}&{学号2} = {支持的网络类型}}"
      - YSU_AUTH_USER_201811080333="{201811080333的密码}"
      - YSU_AUTH_USER_{学号2}="{学号2的密码}"
      - wh_access_token="{钉钉的Access Token}"
      - wh_secret="{钉钉的Secret}"

    # NIGHT_PAUSE用来控制是否夜间暂停工作，只有内容是1的时候才起作用
    # 本科生暑假不断电，但是断网
      - NIGHT_PAUSE="1"

    # 下面两个时间参数优先级均低于 NIGHT_PAUSE
      - Logout_Time_Start="{钉钉的Secret}"
      - Logout_Time_End="{钉钉的Secret}"

      - StartWork_Time_Start="{钉钉的Secret}"
      - StartWork_Time_End="{钉钉的Secret}"

# 请将本文件的后戳名改为yml
